# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(default=datetime.datetime(2017, 6, 18, 8, 26, 42, 590640, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
    ]
